name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [ gcc, clang ]

    steps:
      - uses: actions/checkout@v4
      - name: Make grabexif
        run: make -C grabexif CC=${{ matrix.compiler }}
